"use client";

import { useEffect, useMemo, useState } from "react";
import { createUmi } from "@metaplex-foundation/umi-bundle-defaults";
import { create, createCollection, fetchAssetV1, fetchCollectionV1, mplCore } from "@metaplex-foundation/mpl-core";
import { createGenericFile, generateSigner, publicKey } from "@metaplex-foundation/umi";
import { walletAdapterIdentity } from "@metaplex-foundation/umi-signer-wallet-adapters";
import { irysUploader } from "@metaplex-foundation/umi-uploader-irys/web";
import { Connection, PublicKey, Transaction, VersionedTransaction, clusterApiUrl } from "@solana/web3.js";
import { createSolanaClient, type SolanaClient } from "@metamask/connect-solana";
import { BadgeCheck, CheckCircle2, Copy, ExternalLink, FileBadge2, LoaderCircle, Search, ShieldCheck, Wallet } from "lucide-react";

const RPC_URL = clusterApiUrl("devnet");
const COLLECTION_KEY = "nftstart.collection";
const CERTIFICATES_KEY = "nftstart.certificates";

type PhantomProvider = {
  isPhantom?: boolean;
  publicKey?: PublicKey;
  connect: () => Promise<{ publicKey: PublicKey }>;
  signTransaction: (transaction: unknown) => Promise<unknown>;
  signAllTransactions: (transactions: unknown[]) => Promise<unknown[]>;
  signMessage?: (message: Uint8Array) => Promise<{ signature: Uint8Array }>;
};
type AdminWalletAdapter = {
  publicKey?: PublicKey;
  signTransaction: (transaction: Transaction | VersionedTransaction) => Promise<Transaction | VersionedTransaction>;
  signAllTransactions: (transactions: (Transaction | VersionedTransaction)[]) => Promise<(Transaction | VersionedTransaction)[]>;
  signMessage?: (message: Uint8Array) => Promise<{ signature: Uint8Array }>;
};
type StandardAccount = { address: string };
type StandardConnectFeature = { connect: () => Promise<{ accounts: readonly StandardAccount[] }> };
type StandardSignTransactionFeature = { signTransaction: (...inputs: { account: StandardAccount; transaction: Uint8Array; chain: "solana:devnet" }[]) => Promise<readonly { signedTransaction: Uint8Array }[]> };
type StandardSignMessageFeature = { signMessage: (...inputs: { account: StandardAccount; message: Uint8Array }[]) => Promise<readonly { signature: Uint8Array }[]> };
type CertificateRecord = { asset:string; collection:string; recipient:string; recipientName:string; certificateNumber:string; program:string; issueDate:string; signature:string; metadataUri:string; createdAt:string; revoked:boolean };
declare global { interface Window { phantom?: { solana?: PhantomProvider } } }
type WebMcpContext = { registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown},options?:{signal?:AbortSignal})=>void|Promise<void> };

const shorten = (value:string,left=5,right=5) => `${value.slice(0,left)}…${value.slice(-right)}`;
const escapeXml = (value:string) => value.replace(/[<>&'\"]/g, (char) => ({"<":"&lt;",">":"&gt;","&":"&amp;","'":"&apos;",'"':"&quot;"}[char]!));

function makeCertificateSvg(data:{recipientName:string;certificateNumber:string;issueDate:string;program:string}) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="1000" viewBox="0 0 1600 1000"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#38236f"/><stop offset="1" stop-color="#9b239c"/></linearGradient></defs><rect width="1600" height="1000" fill="#fffdfc"/><rect width="350" height="1000" fill="url(#g)"/><path d="M0 0h350L0 350z" fill="#ff855f"/><path d="M0 1000h350L0 650z" fill="#4fc2d5"/><path d="M210 0h140L210 140z" fill="#d31758"/><circle cx="1510" cy="90" r="145" fill="#f3effa"/><text x="95" y="470" fill="#fff" font-family="Arial" font-size="26" font-weight="700" letter-spacing="4" transform="rotate(-90 95 470)">STARTUP-COURSE.COM</text><text x="445" y="125" fill="#392b74" font-family="Arial" font-size="26" font-weight="700" letter-spacing="5">KBTU STARTUP INCUBATOR</text><text x="445" y="290" fill="#d31758" font-family="Georgia" font-size="94">СЕРТИФИКАТ</text><text x="445" y="365" fill="#6f6781" font-family="Arial" font-size="28">свидетельствует, что</text><text x="445" y="490" fill="#282338" font-family="Georgia" font-size="66">${escapeXml(data.recipientName)}</text><line x1="445" y1="525" x2="1460" y2="525" stroke="#d9d2e8" stroke-width="2"/><text x="445" y="610" fill="#6f6781" font-family="Arial" font-size="26">успешно прошёл(ла) программу инкубации</text><text x="445" y="675" fill="#392b74" font-family="Arial" font-size="38" font-weight="700">${escapeXml(data.program)}</text><rect x="445" y="765" width="430" height="82" rx="41" fill="#efeafb"/><text x="490" y="817" fill="#392b74" font-family="Arial" font-size="24">№ ${escapeXml(data.certificateNumber)} · ${escapeXml(data.issueDate)}</text><text x="1450" y="815" text-anchor="end" fill="#392b74" font-family="Arial" font-size="23" font-weight="700">SOLANA DEVNET</text><text x="1450" y="855" text-anchor="end" fill="#8d85a0" font-family="Arial" font-size="20">Проверяемый NFT-сертификат</text></svg>`;
}

const getPhantom = () => typeof window === "undefined" ? undefined : window.phantom?.solana;
function createAdminUmi(provider:AdminWalletAdapter) {
  const adapter = { publicKey:provider.publicKey, signTransaction:provider.signTransaction.bind(provider), signAllTransactions:provider.signAllTransactions.bind(provider), signMessage:provider.signMessage?.bind(provider) };
  return createUmi(RPC_URL).use(mplCore()).use(walletAdapterIdentity(adapter as never)).use(irysUploader({address:"https://devnet.irys.xyz",providerUrl:RPC_URL,timeout:60_000}));
}

export default function Home() {
  const [walletAddress,setWalletAddress]=useState(""); const [walletName,setWalletName]=useState<"Phantom"|"MetaMask"|"">(""); const [walletPicker,setWalletPicker]=useState(false); const [walletAdapter,setWalletAdapter]=useState<AdminWalletAdapter|null>(null); const [balance,setBalance]=useState<number|null>(null); const [collection,setCollection]=useState("");
  const [records,setRecords]=useState<CertificateRecord[]>([]); const [mode,setMode]=useState<"issue"|"verify">("issue"); const [busy,setBusy]=useState(""); const [status,setStatus]=useState(""); const [error,setError]=useState(""); const [verifyAddress,setVerifyAddress]=useState("");
  const [verifiedAsset,setVerifiedAsset]=useState<null|{name:string;owner:string;uri:string;asset:string;collection?:string}>(null);
  const [form,setForm]=useState({recipientName:"",certificateNumber:"",issueDate:new Date().toISOString().slice(0,10),program:"Технологическое предпринимательство и стартапы",recipient:""});
  const connection=useMemo(()=>new Connection(RPC_URL,"confirmed"),[]);

  useEffect(()=>{ setCollection(localStorage.getItem(COLLECTION_KEY)??""); try{setRecords(JSON.parse(localStorage.getItem(CERTIFICATES_KEY)??"[]"))}catch{setRecords([])} const certificate=new URLSearchParams(window.location.search).get("certificate"); if(certificate){setVerifyAddress(certificate);setMode("verify");void verifyCertificate(certificate)} },[]);
  useEffect(()=>{const context=(document as Document&{modelContext?:WebMcpContext}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"prepare_certificate_issue",title:"Подготовить выпуск сертификата",description:"Заполняет видимую форму выпуска NFT-сертификата. Транзакция не отправляется: администратор должен проверить данные и подтвердить выпуск в подключённом кошельке.",inputSchema:{type:"object",properties:{recipientName:{type:"string"},certificateNumber:{type:"string"},issueDate:{type:"string"},program:{type:"string"},recipient:{type:"string"}},required:["recipientName","certificateNumber","issueDate","program","recipient"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const value=input as Record<string,string>;if(!value.recipientName||!value.certificateNumber||!value.issueDate||!value.program||!value.recipient)throw new Error("Все поля обязательны");setForm({recipientName:value.recipientName,certificateNumber:value.certificateNumber,issueDate:value.issueDate,program:value.program,recipient:value.recipient});setMode("issue");return{status:"prepared",requiresAdminConfirmation:true}}},{signal:lifecycle.signal}));return()=>lifecycle.abort()},[]);
  async function refreshBalance(address:string){const lamports=await connection.getBalance(new PublicKey(address));setBalance(lamports/1_000_000_000)}
  async function connectPhantom(){setError("");setWalletPicker(false);const provider=getPhantom();if(!provider?.isPhantom){setError("Phantom не найден. Установите расширение или откройте приложение во встроенном браузере Phantom.");return}try{const result=await provider.connect();const address=result.publicKey.toBase58();setWalletAdapter(provider as AdminWalletAdapter);setWalletName("Phantom");setWalletAddress(address);await refreshBalance(address)}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось подключить Phantom")}}
  async function connectMetaMask(){setError("");setWalletPicker(false);setBusy("connect");try{const client:SolanaClient=await createSolanaClient({dapp:{name:"Startup Course NFT Certificates",url:window.location.href},api:{supportedNetworks:{devnet:RPC_URL}},analytics:{enabled:false}});const wallet=client.getWallet();const connectFeature=wallet.features["standard:connect"] as StandardConnectFeature|undefined;const signFeature=wallet.features["solana:signTransaction"] as StandardSignTransactionFeature|undefined;const messageFeature=wallet.features["solana:signMessage"] as StandardSignMessageFeature|undefined;if(!connectFeature||!signFeature)throw new Error("MetaMask не предоставил функции Solana");const {accounts}=await connectFeature.connect();const account=accounts[0];if(!account)throw new Error("В MetaMask не выбран Solana-аккаунт");const deserialize=(original:Transaction|VersionedTransaction,bytes:Uint8Array)=>original instanceof VersionedTransaction?VersionedTransaction.deserialize(bytes):Transaction.from(bytes);const adapter:AdminWalletAdapter={publicKey:new PublicKey(account.address),async signTransaction(transaction){const [output]=await signFeature.signTransaction({account,transaction:transaction.serialize({requireAllSignatures:false,verifySignatures:false}),chain:"solana:devnet"});return deserialize(transaction,output.signedTransaction)},async signAllTransactions(transactions){const outputs=await signFeature.signTransaction(...transactions.map(transaction=>({account,transaction:transaction.serialize({requireAllSignatures:false,verifySignatures:false}),chain:"solana:devnet" as const})));return outputs.map((output,index)=>deserialize(transactions[index],output.signedTransaction))},signMessage:messageFeature?async(message)=>{const [output]=await messageFeature.signMessage({account,message});return{signature:output.signature}}:undefined};setWalletAdapter(adapter);setWalletName("MetaMask");setWalletAddress(account.address);await refreshBalance(account.address)}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось подключить MetaMask")}finally{setBusy("")}}
  async function requestAirdrop(){if(!walletAddress)return;setBusy("airdrop");setError("");try{const signature=await connection.requestAirdrop(new PublicKey(walletAddress),1_000_000_000);const blockhash=await connection.getLatestBlockhash();await connection.confirmTransaction({signature,...blockhash},"confirmed");await refreshBalance(walletAddress);setStatus("Получен 1 Devnet SOL")}catch{setError("Devnet faucet отклонил запрос. Пополните кошелёк через faucet.solana.com.")}finally{setBusy("")}}
  async function ensureCollection(){if(collection)return collection;if(!walletAdapter?.publicKey)throw new Error("Сначала подключите кошелёк администратора");setStatus("Создаём официальную коллекцию…");const umi=createAdminUmi(walletAdapter);const signer=generateSigner(umi);const uri=await umi.uploader.uploadJson({name:"KBTU Startup Incubator Certificates",description:"Official certificate collection on Solana Devnet",image:""});await createCollection(umi,{collection:signer,name:"KBTU Startup Incubator Certificates",uri}).sendAndConfirm(umi);const address=signer.publicKey.toString();localStorage.setItem(COLLECTION_KEY,address);setCollection(address);return address}

  async function issueCertificate(event:React.FormEvent){event.preventDefault();setError("");setStatus("");try{if(!walletAddress||!walletAdapter?.publicKey)throw new Error("Сначала подключите кошелёк администратора");new PublicKey(form.recipient);if(!form.recipientName.trim()||!form.certificateNumber.trim())throw new Error("Заполните ФИО и номер сертификата");if(records.some(item=>item.certificateNumber===form.certificateNumber.trim()))throw new Error("Сертификат с таким номером уже выпускался на этом устройстве");setBusy("issue");const umi=createAdminUmi(walletAdapter);const collectionAddress=await ensureCollection();const collectionAccount=await fetchCollectionV1(umi,publicKey(collectionAddress));setStatus("Загружаем карточку и метаданные…");const svg=makeCertificateSvg(form);const image=(await umi.uploader.upload([createGenericFile(new TextEncoder().encode(svg),`certificate-${form.certificateNumber}.svg`,{contentType:"image/svg+xml"})]))[0];const assetSigner=generateSigner(umi);const name=`KBTU Certificate #${form.certificateNumber.trim()}`;const metadataUri=await umi.uploader.uploadJson({name,description:`Сертификат программы «${form.program}», выданный KBTU Startup Incubator`,image,external_url:`${window.location.origin}/?certificate=${assetSigner.publicKey}`,attributes:[{trait_type:"Recipient",value:form.recipientName.trim()},{trait_type:"Certificate Number",value:form.certificateNumber.trim()},{trait_type:"Program",value:form.program.trim()},{trait_type:"Issue Date",value:form.issueDate},{trait_type:"Issuer",value:"KBTU Startup Incubator"},{trait_type:"Network",value:"Solana Devnet"}],properties:{files:[{uri:image,type:"image/svg+xml"}],category:"image"}});setStatus(`Подтвердите выпуск в ${walletName}…`);const result=await create(umi,{asset:assetSigner,collection:collectionAccount,owner:publicKey(form.recipient),name,uri:metadataUri,plugins:[{type:"PermanentFreezeDelegate",frozen:true,authority:{type:"Address",address:publicKey(walletAddress)}},{type:"Attributes",attributeList:[{key:"certificate_number",value:form.certificateNumber.trim()},{key:"recipient",value:form.recipientName.trim()},{key:"status",value:"valid"}]}]}).sendAndConfirm(umi);const record:CertificateRecord={asset:assetSigner.publicKey.toString(),collection:collectionAddress,recipient:form.recipient,recipientName:form.recipientName.trim(),certificateNumber:form.certificateNumber.trim(),program:form.program.trim(),issueDate:form.issueDate,signature:Array.from(result.signature).join("."),metadataUri,createdAt:new Date().toISOString(),revoked:false};const next=[record,...records];setRecords(next);localStorage.setItem(CERTIFICATES_KEY,JSON.stringify(next));setStatus(`Сертификат #${record.certificateNumber} выпущен`);setVerifyAddress(record.asset);setForm(current=>({...current,recipientName:"",certificateNumber:"",recipient:""}));await refreshBalance(walletAddress)}catch(reason){setError(reason instanceof Error?reason.message:"Выпуск не выполнен")}finally{setBusy("")}}
  async function verifyCertificate(address=verifyAddress){setBusy("verify");setError("");setVerifiedAsset(null);try{const umi=createUmi(RPC_URL).use(mplCore());const asset=await fetchAssetV1(umi,publicKey(address.trim()));const collectionAddress=asset.updateAuthority.type==="Collection"&&asset.updateAuthority.address?asset.updateAuthority.address.toString():undefined;setVerifiedAsset({name:asset.name,owner:asset.owner.toString(),uri:asset.uri,asset:address.trim(),collection:collectionAddress})}catch{setError("NFT не найден в Solana Devnet или адрес введён неверно")}finally{setBusy("")}}
  function toggleRevoked(asset:string){const next=records.map(item=>item.asset===asset?{...item,revoked:!item.revoked}:item);setRecords(next);localStorage.setItem(CERTIFICATES_KEY,JSON.stringify(next))}
  async function copy(value:string){await navigator.clipboard.writeText(value);setStatus("Скопировано")}
  const localRecord=records.find(item=>item.asset===verifiedAsset?.asset);const collectionMatches=Boolean(verifiedAsset?.collection&&collection&&verifiedAsset.collection===collection);

  return <main className="app-shell"><header className="topbar"><div className="brand"><img className="brand-logo" src="https://startup-course.com/images/tild3261-3537-4565-a263-323130366532__3.svg" alt="Startup Course"/><div><strong>STARTUP-COURSE.COM</strong><small>NFT CERTIFICATES</small></div></div><span className="network-pill"><i/> SOLANA DEVNET</span><div className="wallet-zone">{walletAddress?<><span className="balance">{balance?.toFixed(3)??"—"} SOL</span><button className="wallet-button connected" title={walletName}><Wallet size={16}/>{walletName} · {shorten(walletAddress)}</button></>:<div className="wallet-picker-wrap"><button className="wallet-button" onClick={()=>setWalletPicker(value=>!value)} disabled={busy==="connect"}><Wallet size={16}/>{busy==="connect"?"ПОДКЛЮЧЕНИЕ…":"ПОДКЛЮЧИТЬ КОШЕЛЁК"}</button>{walletPicker&&<div className="wallet-picker"><button onClick={connectPhantom}><strong>Phantom</strong><span>Solana · расширение</span></button><button onClick={connectMetaMask}><strong>MetaMask</strong><span>Solana · Devnet</span></button></div>}</div>}</div></header>
  <div className="workspace"><aside className="sidebar"><nav><button className={mode==="issue"?"active":""} onClick={()=>setMode("issue")}><FileBadge2 size={18}/>Выпуск</button><button className={mode==="verify"?"active":""} onClick={()=>setMode("verify")}><Search size={18}/>Проверка</button></nav><div className="collection-card"><span>Официальная коллекция</span><strong>{collection?shorten(collection,7,7):"Ещё не создана"}</strong>{collection&&<a href={`https://explorer.solana.com/address/${collection}?cluster=devnet`} target="_blank" rel="noreferrer">Открыть в Explorer <ExternalLink size={13}/></a>}</div></aside>
  <section className="content">{status&&<div className="notice success"><CheckCircle2 size={18}/>{status}</div>}{error&&<div className="notice error">{error}</div>}
  {mode==="issue"?<><div className="page-heading"><div><p>STARTUP-COURSE · ADMIN</p><h1>Выпустить сертификат</h1><span>От идеи до готового продукта — теперь с подтверждением в Solana.</span></div>{walletAddress&&(balance??0)<.05&&<button className="secondary-button" onClick={requestAirdrop} disabled={Boolean(busy)}>{busy==="airdrop"&&<LoaderCircle className="spin" size={16}/>}Получить Devnet SOL</button>}</div><div className="grid-layout"><form className="panel form-panel" onSubmit={issueCertificate}><label>ФИО получателя<input required value={form.recipientName} onChange={e=>setForm({...form,recipientName:e.target.value})} placeholder="Токсеитова Аружан"/></label><div className="row"><label>Номер<input required value={form.certificateNumber} onChange={e=>setForm({...form,certificateNumber:e.target.value})} placeholder="320"/></label><label>Дата<input required type="date" value={form.issueDate} onChange={e=>setForm({...form,issueDate:e.target.value})}/></label></div><label>Программа<input required value={form.program} onChange={e=>setForm({...form,program:e.target.value})}/></label><label>Solana-адрес получателя<input required className="mono" value={form.recipient} onChange={e=>setForm({...form,recipient:e.target.value.trim()})} placeholder="Введите публичный адрес"/></label><div className="warning"><ShieldCheck size={19}/><span>NFT будет сразу отправлен получателю и заблокирован от передачи.</span></div><button className="primary-button" disabled={Boolean(busy)}>{busy==="issue"?<LoaderCircle className="spin" size={18}/>:<BadgeCheck size={18}/>}ВЫПУСТИТЬ NFT</button></form><div className="panel preview-panel"><span className="eyebrow">ПРЕДПРОСМОТР</span><div className="certificate-preview"><span>KBTU STARTUP INCUBATOR</span><h2>СЕРТИФИКАТ</h2><p>свидетельствует, что</p><h3>{form.recipientName||"Имя получателя"}</h3><hr/><p>успешно прошёл(ла) программу инкубации</p><strong>{form.program}</strong><footer>№ {form.certificateNumber||"—"}<b>{form.issueDate}</b></footer></div></div></div>
  <section className="records-section"><div className="section-heading"><h2>Последние выпуски</h2><span>{records.length}</span></div>{records.length===0?<div className="empty-state">После первого выпуска сертификат появится здесь.</div>:<div className="records">{records.map(item=><article key={item.asset}><div className="record-icon"><FileBadge2 size={18}/></div><div className="record-main"><strong>{item.recipientName}</strong><small>#{item.certificateNumber} · {item.issueDate}</small></div><span className={item.revoked?"state revoked":"state"}>{item.revoked?"Отозван":"Действителен"}</span><button title="Скопировать адрес" onClick={()=>copy(item.asset)}><Copy size={16}/></button><button onClick={()=>toggleRevoked(item.asset)}>{item.revoked?"Вернуть":"Отозвать"}</button><a href={`https://explorer.solana.com/address/${item.asset}?cluster=devnet`} target="_blank" rel="noreferrer"><ExternalLink size={16}/></a></article>)}</div>}</section></>:<div className="verify-wrap"><div className="page-heading"><div><p>ПУБЛИЧНАЯ ПРОВЕРКА</p><h1>Проверить сертификат</h1></div></div><div className="panel verify-panel"><label>Адрес NFT<div className="search-row"><input className="mono" value={verifyAddress} onChange={e=>setVerifyAddress(e.target.value.trim())} placeholder="Введите адрес Core Asset"/><button className="primary-button" onClick={()=>verifyCertificate()} disabled={busy==="verify"}>{busy==="verify"?<LoaderCircle className="spin" size={18}/>:<Search size={18}/>}Проверить</button></div></label></div>{verifiedAsset&&<div className="panel result-card"><div className={localRecord?.revoked?"result-symbol revoked":"result-symbol"}>{localRecord?.revoked?"!":<BadgeCheck size={34}/>}</div><div><span className="eyebrow">РЕЗУЛЬТАТ ПРОВЕРКИ</span><h2>{verifiedAsset.name}</h2><p className={localRecord?.revoked?"result-status revoked":"result-status"}>{localRecord?.revoked?"Сертификат отозван":collectionMatches?"Подлинный сертификат коллекции":"NFT найден, коллекция не подтверждена на этом устройстве"}</p><dl><div><dt>Владелец</dt><dd>{verifiedAsset.owner}</dd></div><div><dt>Коллекция</dt><dd>{verifiedAsset.collection??"Без коллекции"}</dd></div><div><dt>Метаданные</dt><dd><a href={verifiedAsset.uri} target="_blank" rel="noreferrer">Открыть JSON <ExternalLink size={13}/></a></dd></div></dl><a className="explorer-link" href={`https://explorer.solana.com/address/${verifiedAsset.asset}?cluster=devnet`} target="_blank" rel="noreferrer">Открыть в Solana Explorer <ExternalLink size={15}/></a></div></div>}</div>}</section></div></main>;
}
